/* DO NOT EDIT THIS FILE!
This is the main "game" file.
This file holds important things to the HTML file.
This includes:
  How the game works,
  Certain variables,
  Updating the HTML,
  And much more.
Editing this file may break certain parts of the game and will require a complete reinstall.
*/
const in0 = document.getElementById('in0');
const in1 = document.getElementById('in1');
const in2 = document.getElementById('in2');
const in3 = document.getElementById('in3');
const in4 = document.getElementById('in4');
const in5 = document.getElementById('in5');
var display = {
  updateScore: function () {
    document.getElementById("demo").innerHTML = game.score;
  },
  newDisplay: () => {
    if (game.score >= 1000000) {
      var newScore = Math.round(game.score / 1000000)
      document.getElementById("demo").innerHTML = newScore + " million";
    
      document.getElementById("con").innerHTML = "Wulzys profits are 777x more efficent.";
    }
    if (game.score >= 1000000000) {
      var newScore2 = Math.round(game.score / 1000000000)
      document.getElementById("demo").innerHTML = newScore2 + " billion";
      document.getElementById("con").innerHTML = "Wulzys profits are 7777x more efficent.";
    }
    if (game.score >= 1000000000000) {
      var newScore2 = Math.round(game.score / 1000000000000)
      document.getElementById("demo").innerHTML = newScore2 + " trillion";
      document.getElementById("con").innerHTML = "Wulzys profits are 77777x more efficent.";
    }
    if (game.score >= 10 ** 15) {
      var newScore2 = Math.round(game.score / 10 ** 15)
      document.getElementById("demo").innerHTML = newScore2 + " quadrillion";
    }
    if (game.score >= 10 ** 18) {
      var newScore2 = Math.round(game.score / 10 ** 18)
      document.getElementById("demo").innerHTML = newScore2 + " quintillion";
    }
    if (game.score >= 10 ** 21) {
      var newScore2 = Math.round(game.score / 10 ** 21)
      document.getElementById("demo").innerHTML = newScore2 + " sextillion";
    }
    if (game.score >= 10 ** 24) {
      var newScore2 = Math.round(game.score / 10 ** 24)
      document.getElementById("demo").innerHTML = newScore2 + " septillion";
    }
    if (game.score >= 10 ** 27) {
      var newScore2 = Math.round(game.score / 10 ** 27)
      document.getElementById("demo").innerHTML = newScore2 + " octillion";
    }
    if (game.score >= 10 ** 30) {
      var newScore2 = Math.round(game.score / 10 ** 27)
      document.getElementById("demo").innerHTML = newScore2 + " nonillion";
    }
    if (game.score >= 10 ** 33) {
      var newScore2 = Math.round(game.score / 10 ** 27)
      document.getElementById("demo").innerHTML = newScore2 + " decillion";
      document.getElementById("con").innerHTML = "Wulzys profits are 7777777x more efficent.";
    }
  }
}
const game = {
  score: 0,
  clickValue: 1,
  comps: 0,
  megaHackGuy: 0,
  jamesus: 0,
  feds: 0,
  painoguys: 0,
  creators: 0,
  addToScore: function (amuount) {
    if (amuount > 0) {
      this.score += amuount;
      this.totalScore += amuount;
    }
    display.updateScore();
    setInterval(function () {
      if (game.score >= 1000) {
        game.clickValue = 2;
        building.income[0] = 1;
        building.income[1] = 4;
        building.income[2] = 20;
        building.income[3] = 200;
        building.income[4] = 4000;
        building.income[5] = 10000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        document.getElementById("con").innerHTML = "Wulzys profits are 2x more efficent.";
      }
      if (game.score >= 5000) {
        game.clickValue = 4;
        building.income[0] = 2;
        building.income[1] = 8;
        building.income[2] = 40;
        building.income[3] = 400;
        building.income[4] = 8000;
        building.income[5] = 20000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        document.getElementById("con").innerHTML = "Wulzys profits are 4x more efficent.";
      }
      if (game.score >= 20000) {
        game.clickValue = 8;
        building.income[0] = 4;
        building.income[1] = 16;
        building.income[2] = 80;
        building.income[3] = 800;
        building.income[4] = 16000;
        building.income[5] = 40000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        document.getElementById("con").innerHTML = "Wulzys profits are 8x more efficent.";
      }
      if (game.score >= 50000) {
        game.clickValue = 16;
        building.income[0] = 8;
        building.income[1] = 32;
        building.income[2] = 160;
        building.income[3] = 1600;
        building.income[4] = 32000;
        building.income[5] = 80000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        document.getElementById("con").innerHTML = "Wulzys profits are 16x more efficent.";
      }
      if (game.score >= 100000) {
        game.clickValue = 32;
        building.income[0] = 16;
        building.income[1] = 64;
        building.income[2] = 320;
        building.income[3] = 3200;
        building.income[4] = 64000;
        building.income[5] = 160000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        document.getElementById("con").innerHTML = "Wulzys profits are 32x more efficent.";
      }
      if (game.score >= 1000000) {
        game.clickValue = 777;
        building.income[0] = 388.5;
        building.income[1] = 1554;
        building.income[2] = 7770;
        building.income[3] = 77700;
        building.income[4] = 155400;
        building.income[5] = 3885000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        display.newDisplay();
      }
      if (game.score >= 1000000000) {
        game.clickValue = 7777;
        building.income[0] = 3888.5;
        building.income[1] = 15554;
        building.income[2] = 77770;
        building.income[3] = 777700;
        building.income[4] = 1555400;
        building.income[5] = 38885000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        display.newDisplay();
      }
      if (game.score >= 10 ** 12) {
        game.clickValue = 77777;
        building.income[0] = 38888.5;
        building.income[1] = 155554;
        building.income[2] = 777770;
        building.income[3] = 7777700;
        building.income[4] = 15555400;
        building.income[5] = 388885000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        display.newDisplay();
      }
      if (game.score >= 10 ** 33) {
        game.clickValue = 7777777;
        building.income[0] = 3888888.5;
        building.income[1] = 15555554;
        building.income[2] = 77777770;
        building.income[3] = 777777700;
        building.income[4] = 1555555400;
        building.income[5] = 38888885000;
        in0.innerHTML = building.income[0]
        in1.innerHTML = building.income[1]
        in2.innerHTML = building.income[2]
        in3.innerHTML = building.income[3]
        in4.innerHTML = building.income[4]
        in5.innerHTML = building.income[5] * 4
        display.newDisplay();
      }
    }, 1);
  },
  addMhGs: () => {
    const place = document.getElementById("mhgs")
    place.addEventListener("click", function () {
      if (game.score >= building.cost[1]) {
        game.score = game.score - building.cost[1]
        building.cost[1] = Math.round(building.cost[1] * 1.1)
        building.income[1] += Math.round(building.count[1] * 1.005)
        game.megaHackGuy += 1
        document.getElementById('mhdudes').innerHTML = game.megaHackGuy;
        document.getElementById('cool2').innerHTML = building.cost[1];
        setInterval(function () {
          game.score += building.income[1] * game.megaHackGuy
          display.updateScore()
        }, 1000)
      }
    })
  },
  addComps: () => {
    const comp = document.getElementById("comp")
    comp.addEventListener("click", function () {
      if (game.score >= building.cost[0]) {
        game.score = game.score - building.cost[0]
        building.cost[0] = Math.round(building.cost[0] * 1.05)
        building.income[0] += Math.round(building.count[0] * 1.0002)
        game.comps += 1
        document.getElementById('comps').innerHTML = game.comps;
        document.getElementById('cool').innerHTML = building.cost[0];
        setInterval(function () {
          game.score += building.income[0] * game.comps
          display.updateScore();
        }, 1000)
      }
    })
  },
  addJamesus: () => {
    const place = document.getElementById("Jamesus")
    place.addEventListener("click", function () {
      if (game.score >= building.cost[2]) {
        game.score = game.score - building.cost[2]
        building.cost[2] = Math.round(building.cost[2] * 1.2)
        building.income[2] += Math.round(building.count[2] * 1.001)
        game.jamesus += 1
        document.getElementById('jame').innerHTML = game.jamesus;
        document.getElementById('cool3').innerHTML = building.cost[2];
        setInterval(function () {
          game.score += building.income[2] * game.jamesus
          display.updateScore();
        }, 1000)
      }
    })
  },
  addFeds: () => {
    const place = document.getElementById("fedman")
    place.addEventListener("click", function () {
      if (game.score >= building.cost[3]) {
        game.score = game.score - building.cost[3]
        building.cost[3] = Math.round(building.cost[3] * 1.25)
        building.income[3] += Math.round(building.count[3] * 1.017)
        game.feds += 1
        document.getElementById('feds').innerHTML = game.feds;
        document.getElementById('cool4').innerHTML = building.cost[3];
        setInterval(function () {
          game.score += building.income[3] * game.feds
          display.updateScore()
        }, 1000)
      }
    })
  },
  addPianos: () => {
    const place = document.getElementById("piano")
    place.addEventListener("click", function () {
      if (game.score >= building.cost[4]) {
        game.score = game.score - building.cost[4]
        building.cost[4] = Math.round(building.cost[4] * 1.275)
        building.income[4] += Math.round(building.count[4] * 1.04)
        game.painoguys += 1
        document.getElementById('pianos').innerHTML = game.painoguys;
        document.getElementById('cool5').innerHTML = building.cost[4];
        setInterval(function () {
          game.score += building.income[4] * game.painoguys
          display.updateScore()
        }, 1000)
      }
    })
  },
  addCreator: () => {
    const place = document.getElementById("creator")
    place.addEventListener("click", function () {
      if (game.score >= building.cost[5]) {
        game.score = game.score - building.cost[5]
        building.cost[5] = Math.round(building.cost[5] * 1.3)
        building.income[5] += Math.round(building.count[5] * 1.1)
        game.creators += 1
        document.getElementById('creators').innerHTML = game.creators;
        document.getElementById('cool6').innerHTML = building.cost[5];
        setInterval(function () {
          game.score += building.income[5] * game.creators
          display.updateScore()
        }, 250)
      }
    })
  },
}
const building = {
  name: [
    "Cool Progammer",
    "Mega Hack Guy",
    "Jamesus",
    "Fedman",
    "Piano Guy",
    "Da Creator"
  ],
  image: [
    "comuputer.jpg",
    "abs.png",
    "dollarstorejesus.jpg",
    "download.jpg",
    "pianoguy.jpg",
    "creator.jpg"
  ],
  count: [
    0,
    0,
    0,
    0,
    0,
    0
  ],
  income: [
    0.5,
    2,
    10,
    100,
    2000,
    5000,
  ],
  cost: [
    10,
    100,
    1000,
    10000,
    100000,
    500000
  ],
};
let colors = ["red", "orange", "yellow", "green", "blue", "purple", "magenta", "midnightblue", "aqua", "maroon", "orchid", "black", "olive", "palegreen", "seagreen", "lavender"]
let body = document.getElementById("body")
let container = document.getElementById("container")
var buttons = Array.from(document.getElementsByClassName("button"));
let x = Math.floor(Math.random() * colors.length) + 1
function rng() {
  console.log(x)
  console.log(buttons)
  if (x == 1) {
    body.style.background = colors[0];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[0];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 2) {
    body.style.background = colors[1];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[1];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 3) {
    body.style.background = colors[2];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[2];
      buttons.style.color = "black";
    });
  }
  else if (x == 4) {
    body.style.background = colors[3];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[3];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 5) {
    body.style.background = colors[4];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[4];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 6) {
    body.style.background = colors[5];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[5];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 7) {
    body.style.background = colors[6];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[6];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 8) {
    body.style.background = colors[7];
    container.style.color = "white";
    buttons.forEach(buttons => {
      buttons.style.background = colors[7];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 9) {
    body.style.background = colors[8];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[8];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 10) {
    body.style.background = colors[9];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[9];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 11) {
    body.style.background = colors[10];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[10];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 12) {
      body.style.background = colors[11];
    container.style.color = "white";
    buttons.forEach(buttons => {
      buttons.style.background = colors[11];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 13) {
    body.style.background = colors[12];
    container.style.color = "white";
    buttons.forEach(buttons => {
      buttons.style.background = colors[12];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 14) {
    body.style.background = colors[13];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[13];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 15) {
    body.style.background = colors[14];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[14];
      buttons.style.color = "yellow"
    });
  }
  else if (x == 16) {
    body.style.background = colors[15];
    container.style.color = "black";
    buttons.forEach(buttons => {
      buttons.style.background = colors[15];
      buttons.style.color = "black"
    });
  }
};
let savedGame = {
    "score":  game.score,
    "clickValue": game.clickValue,
    "comps": game.comps,
    "megaHackGuy": game.megaHackGuy,
    "buildingCount": building.count,
    "buildingCost": building.cost,
    "buildingIncome": building.income
}
var myJSON = JSON.stringify(savedGame)
var newJSON = JSON.parse(myJSON);
function saveGame() {
var counter = 0
  do {
  let savedGame = {
    "score": game.score,
    "clickValue": game.clickValue,
    "comps": game.comps,
    "megaHackGuy": game.megaHackGuy,
    "buildingCount": building.count,
    "buildingCost": building.cost,
    "buildingIncome": building.income
    }
    var myJSON = JSON.stringify(savedGame)
    localStorage.setItem("savedGame", myJSON)
    counter = 1
    window.onload = () => {
      var newJSON = JSON.parse(myJSON);
      localStorage.setItem("savedGame", newJSON)
      localStorage.getItem('savedGame');
      game.score = savedGame.score;
      game.clickValue = savedGame.clickValue;
      game.comps = savedGame.comps;
      game.megaHackGuy = savedGame.megaHackGuy;
      building.cost = savedGame.buildingCost;
      building.count = savedGame.buildingCount;
      building.income = savedGame.buildingIncome;
    }
    console.log(localStorage)
  } while (counter == 0)
  open('./download.html')
}
function hexthing() {
  let color = document.getElementById("colorpanel").value
  document.body.style.background = color
}
function hexthing2() {
  let color2 = document.getElementById("colorpanel2").value
  buttons.forEach(buttons => {
    buttons.style.color = color2;
  });
}
function hexthing3() {
  let color3 = document.getElementById("colorpanel3").value
  buttons.forEach(buttons => {
    buttons.style.background = color3;
  });
}
function loadGame() {
  savedGame = JSON.parse(myJSON)
  game.score = savedGame.score;
  game.clickValue = savedGame.clickValue;
  game.comps = savedGame.comps;
  game.megaHackGuy = savedGame.megaHackGuy;
  building.cost = savedGame.buildingCost;
  building.count = savedGame.buildingCount;
  building.income = savedGame.buildingIncome;
}